# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df295a18a09b4b8ae3a491cbb882d17580b9b7ecbdaab964726ba4f4a5a5788765ed0d0e71ebee1b8f9e196bf33639adc91b2f42ff89833a73e2883a92ffac2b

test:
  secret_key_base: b8c913a9d2d69ae33df0e447eb15cdb0d3644648a3828d6475fc4a4d3b8dc5eec2751880bffb3f29f47b0720a1c047605cd022bf8d70d544fb5cb6b4f59d0aff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
